version: "3.8"

services:
  preprocessor:
    image: retinaface-preproc:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.preprocess
    volumes:
      - .:/app

  predictor:
    build:
      context: .
      dockerfile: docker/Dockerfile.basemodel
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - preprocessor
