name: model_running
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.16
  - pip
  - numpy=1.24.3
  - matplotlib
  - albumentations
  - opencv
  - scikit-learn
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - grad-cam