FROM python:3.8-slim

WORKDIR /app

COPY requirements_preproc.txt .
COPY dlib-19.22.0.tar.gz .

# Install system packages needed to build dlib
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --upgrade pip

# Install dlib from PyPI (will build from source)
RUN pip install dlib-19.22.0.tar.gz

# Install the rest of the requirements
RUN pip install --no-cache-dir -r requirements_preproc.txt

COPY . .

CMD ["python", "project_name/data/preprocessing.py"]


