services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    command: /bin/bash -c "conda run -n predict_env uvicorn app:app --reload --host 0.0.0.0 --port 8000 & sleep 2 && conda run -n predict_env streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    volumes:
      - ../:/workspace
    environment:
      - PYTHONUNBUFFERED=1