FROM python:3.10-slim

WORKDIR /app

COPY requirements_predict.txt .

RUN pip install --no-cache-dir -r requirements_predict.txt
RUN pip install --no-cache-dir fastapi uvicorn streamlit python-multipart requests pillow

COPY . .

CMD ["bash", "-c", "uvicorn app:app --reload --port 8000 & streamlit run app/streamlit_app.py"]
